### ISSUE TITLE
Multisite fatal error

### ISSUE THREAD

**Issue by mati75** [aaemnnosttv/wp-sqlite-db#13]
When I try activate multisite network, script return error:

```
Uncaught Error: Class 'WP_SQLite_DB\DateInterval' not found in /home/mati75/websites/sqlite.local/wp-content/db.php:517                                                        
Stack trace:
#0 [internal function]: WP_SQLite_DB\PDOSQLiteUDFS->date_sub()
#1 /home/mati75/websites/sqlite.local/wp-content/db.php(1692): PDOStatement->execute()
#2 /home/mati75/websites/sqlite.local/wp-content/db.php(1408): WP_SQLite_DB\PDOEngine->execute_query()
#3 /home/mati75/websites/sqlite.local/wp-content/db.php(2740): WP_SQLite_DB\PDOEngine->query()
#4 /home/mati75/websites/sqlite.local/wp-includes/wp-db.php(2593): WP_SQLite_DB\wpsqlitedb->query()
#5 /home/mati75/websites/sqlite.local/wp-admin/includes/network.php(72): wpdb->get_row()
#6 /home/mati75/websites/sqlite.local/wp-admin/includes/network.php(189): allow_subdirectory_install()
#7 /home/mati75/websites/sqlite.local/wp-admin/network.php(116): network_step1()
#8 {main}
  thrown in /home/mati75/websites/sqlite.local/wp-content/db.php on line 517
```

on SQLite Integration plugin by Kojima Toshiyasu it works fine.

**Comment by mati75** [comment]
Problem resolution:
```
use DateInterval;
```
is missing.

**Comment by aaemnnosttv** [comment]
Hi there and thanks for the report! Would you please open a PR to address this?
