### ISSUE TITLE
Site Health Page Fatal Error

### ISSUE THREAD

**Issue by kk6mrp** [aaemnnosttv/wp-sqlite-db#24]
I'm getting this error when I try to open the Site Health menu under Tools. Is it possible to add a filter for this?

``` sh FastCGI-stderr:PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mysql_get_server_info() in /var/www/example.com/wp-admin/includes/class-wp-site-health.php:213

2021-12-10 10:03:10: (mod_fastcgi.c.451) FastCGI-stderr:Stack trace:
2021-12-10 10:03:10: (mod_fastcgi.c.451) FastCGI-stderr:#0 /var/www/example.com/wp-admin/includes/class-wp-site-health.php(1163): WP_Site_Health->prepare_sql_data()
2021-12-10 10:03:10: (mod_fastcgi.c.451) FastCGI-stderr:#1 /var/www/example.com/wp-admin/includes/class-wp-site-health.php(192): WP_Site_Health->get_test_sql_server()
2021-12-10 10:03:10: (mod_fastcgi.c.451) FastCGI-stderr:#2 /var/www/example.com/wp-admin/includes/class-wp-site-health.php(137): WP_Site_Health->perform_test()
2021-12-10 10:03:10: (mod_fastcgi.c.451) FastCGI-stderr:#3 /var/www/example.com/wp-includes/class-wp-hook.php(303): WP_Site_Health->enqueue_scripts()
2021-12-10 10:03:10: (mod_fastcgi.c.451) FastCGI-stderr:#4 /var/www/example.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
2021-12-10 10:03:10: (mod_fastcgi.c.451) FastCGI-stderr:#5 /var/www/example.com/wp-includes/plugin.php(470): WP_Hook->do_action()
2021-12-10 10:03:10: (mod_fastcgi.c.451) FastCGI-stderr:#6 /var/www/example.com/wp-admin/admin-header.php(102): do_action()
2021-12-10 10:03:10: (mod_fastcgi.c.451) FastCGI-stderr:#7 /var/www/example.com/wp-admin...
```

**Comment by aaemnnosttv** [comment]
> Is it possible to add a filter for this?

The checks for the database in Site Health could probably be filtered/removed/replaced to prevent such an error, I think so. In this case though, WP seems to be calling a function which has been [removed as of PHP 7](https://www.php.net/manual/en/function.mysql-get-server-info.php). 

What version of WP are you running?

**Comment by kk6mrp** [comment]
The latest version.

**Comment by infostud** [comment]
I just replaced the calls to mysql_get_client_info() with a static string '5.6.5'. The version string is checked for support of utf8mb4 and I think is mostly harmless. Similarly for mysql_get_server_info().

**Comment by aaemnnosttv** [comment]
This has been fixed in a recent release; going to the Site Health screen no longer raises a fatal error 👍
