### ISSUE TITLE
General error: 5 database is locked

### ISSUE THREAD

**Issue by icegit** [aaemnnosttv/wp-sqlite-db#7]
Hi,
I have been testing the db.php on Azure Web Apps Free Plan for a few hours, but I can't get it to work. When making a fresh installation I got the below error. It happens exactly in `make_db_sqlite()` function. I even moved the `$pdo->beginTransaction();` and `$pdo->commit();` lines inside the `foreach` loops to have them executed more often, but it doesn't help.  The database size is 0 byte after this error. Do you have any clue?

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 5 database is locked in /home/site/wwwroot/wp-content/db.php:4815
Stack trace:itle=Title --admin_user=hede --admin_password=test --admin_em--allow-root
#0 /home/site/wwwroot/wp-content/db.php(4815): PDO->commit()
#1 /home/site/wwwroot/wp-content/db.php(4862): WP_SQLite_DB\make_db_sqlite()
#2 phar:///home/site/bin/wp-cli.phar/vendor/wp-cli/core-command/src/Core_Command.php(631): wp_install('Title', 'hede', 'hedehede@hot.co...', true, '', 'hedehot')
#3 phar:///home/site/bin/wp-cli.phar/vendor/wp-cli/core-command/src/Core_Command.php(414): Core_Command->do_install(Array)
#4 [internal function]: Core_Command->install(Array, Array)
#5 phar:///home/site/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#7 phar:///home/site/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func(Object(Closure), Array, Array)
#8 phar:///home/s in /home/site/wwwroot/wp-content/db.php on line 4815
Error: There has been a critical error on your website.Learn more about debugging in WordPress. There has been a critical error on your website.
```

**Comment by stefanos82** [comment]
Maybe it expects the right `user:group` permissions and settings?

In my case, where I am on Debian, my settings must be `www-data` for both `user` and `group` to work properly.

**Comment by sec** [comment]
SQLite won't work on network drives without locking features (and those are missing in there). You can try with `nolock` added to connection string as SQLite docs says:
```
nolock: The nolock parameter is a boolean query parameter which if set disables file locking in rollback journal modes. This is useful for accessing a database on a filesystem that does not support locking. Caution: Database corruption might result if two or more processes write to the same database and any one of those processes uses nolock=1.
```

**Comment by aaemnnosttv** [comment]
Thanks for the context @sec ! Closing for now as this does not appear to be related to the drop-in.
